{{- if .Values.headlessService.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "keyval-store.headlessServiceName" . }}
  labels:
    {{- include "keyval-store.labels" . | nindent 4 }}
    service-type: headless
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    {{- include "keyval-store.selectorLabels" . | nindent 4 }}
{{- end }}
